apiVersion: v1
kind: Namespace
metadata:
  name: hamel
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: py-operator
  namespace: hamel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hamel
  name: py-operator
rules:
- apiGroups: [batch]
  resources: [jobs]
  verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: py-operator
  namespace: hamel
subjects:
- kind: ServiceAccount
  name: py-operator
  apiGroup: ""
roleRef:
  kind: Role
  name: py-operator
  apiGroup: rbac.authorization.k8s.io

