apiVersion: batch/v1
kind: Job
metadata:
  name: job-one
  namespace: hamel
spec:
  template:
    spec:
      containers:
      - name: py
        image: python:3.8-alpine
        command: ["python",  "-c", "import time; time.sleep(1); print('success')"]
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: job-two
  namespace: hamel
spec:
  template:
    spec:
      containers:
      - name: py
        image: python:3.8-alpine
        command: ["python",  "-c", "raise Exception('This is an error')"]
      restartPolicy: Never
  backoffLimit: 1
