apiVersion: batch/v1
kind: Job
metadata:
  name: pi-one
  namespace: hamel
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(200)"]
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi-two
  namespace: hamel
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["this is not valid code, so it will fail"]
      restartPolicy: Never
  backoffLimit: 1
