apiVersion: v1
kind: Namespace
metadata:
  name: hamel
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: py-operator
  namespace: hamel
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-operator
  namespace: hamel
  labels:
    app: py-operator
spec:
  replicas: 1 # make sure to not have more than one replicas
  strategy:
    type: Recreate # make sure the old pod is being killed before the new pod is being created
  selector:
    matchLabels:
      app: py-operator
  template:
    metadata:
      labels:
        app: py-operator
    spec:
      serviceAccountName: py-operator
      containers:
      - name: py-operator
        image: py-operator:v1
        imagePullPolicy: IfNotPresent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: hamel
  name: py-operator
rules:
- apiGroups: [batch]
  resources: [jobs]
  verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: py-operator
  namespace: hamel
subjects:
- kind: ServiceAccount
  name: py-operator
  namespace: hamel
  apiGroup: ""
roleRef:
  kind: Role
  name: py-operator
  apiGroup: rbac.authorization.k8s.io
