apiVersion: v1
kind: ServiceAccount
metadata:
  name: py-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-operator
  labels:
    app: py-operator
spec:
  replicas: 1 # make sure to not have more than one replicas
  strategy:
    type: Recreate # make sure the old pod is being killed before the new pod is being created
  selector:
    matchLabels:
      app: py-operator
  template:
    metadata:
      labels:
        app: py-operator
    spec:
      serviceAccountName: py-operator
      containers:
      - name: py-operator
        image: py-operator:v1
        imagePullPolicy: IfNotPresent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: py-operator
rules:
- apiGroups: [batch]
  resources: [jobs]
  verbs: [patch]
- apiGroups: [""]
  resources: [events]
  verbs: ['create']
- apiGroups: ["*"]
  resources: ["*"]
  verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: py-operator
subjects:
- kind: ServiceAccount
  name: py-operator
  namespace: default
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: py-operator
  apiGroup: rbac.authorization.k8s.io